# Generated by Django 6.0.2 on 2026-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identification_number', models.CharField(max_length=16, unique=True)),
                ('stock_keeping_unit', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('status', models.CharField(choices=[('STOCK', 'In stock'), ('SHOWCASE', 'On display'), ('REPAIR', 'To be repaired'), ('SOLD', 'Solded'), ('LOST', 'Item lost')], default='STOCK', max_length=20)),
                ('metal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('PLATINUM', 'Platinum')], max_length=20)),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
