# Generated by Django 6.0.2 on 2026-02-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_keeping_unit',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
