# Generated by Django 6.0.2 on 2026-02-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_stock_keeping_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descripton',
            new_name='description',
        ),
    ]
