# Generated by Django 6.0.2 on 2026-02-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_descripton_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AlterField(
            model_name='item',
            name='image_display',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
    ]
