# Generated by Django 6.0.2 on 2026-02-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_title_alter_item_image_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('STOCK', 'In stock'), ('SHOWCASE', 'On display'), ('SOLD', 'Solded')], default='STOCK', max_length=20),
        ),
    ]
